name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.1
author: Jordan ALCARAZ <jordan.alcarazz@gmail.com>
homepage: https://github.com/ZaraclaJ/audio_recorder

dependencies:
  path: ^1.5.1
  flutter:
    sdk: flutter
  file: ^5.0.4


environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.jordanalcaraz.audiorecorder.audiorecorder
        pluginClass: AudioRecorderPlugin
      ios:
        pluginClass: AudioRecorderPlugin

dev_dependencies:
  path_provider: ^1.1.0